on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Build, Test and maybe Publish
# TODO fix all this 

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache node_modules
      id: cache-modules
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ matrix.node-version }}-${{ runner.OS }}-build-${{ hashFiles('yarn.lock') }}
    - name: Install deps
      if: steps.cache-modules.outputs.cache-hit != 'true'
      run: yarn install
    - name: Unit test
      run: yarn test:unit
    - name: ESLint
      run: yarn test:lint
    - name: Types test
      run: yarn test:types