on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: Push or PR -> main

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ matrix.node-version }}-${{ runner.OS }}-yarn-${{ hashFiles('yarn.lock') }}
    - name: Install deps
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn install
    - name: Building packages
      run: yarn build
    - name: Unit testing
      run: yarn test:unit
    - name: ESLint
      run: yarn test:lint
    - name: Type checking
      run: yarn test:typecheck